version: "3.0"


services:
  postgres_music:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "my_fast_api_music"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql/data
